---
title: "R Notebook"
author: shawshank
date: 4/20/20
output: html_document
---
```{r}
library(bnlearn)
library(Rgraphviz)
# df <- read.csv("data/cleansed_data.csv")
df <- read.csv("data/test.csv")

df$BPB = as.factor(as.character(df$BPB))
df$Beds = as.factor(as.character(df$Beds))
df$Baths = as.factor(as.character(df$Baths))
nrow(df)
```

```{r}
colnames(df)

```


```{r}
model <- lm(Rent ~ Neigh * BPB, df)
model
predict(model, df[4:6,])
df[4:6,c("BPB", "Neigh", "Rent")]

```



```{r}
dag1 <- model2network("[Neigh][BPB][Zest|BPB:Neigh][Rent|BPB:Neigh][ROI|Zest:Rent]")
dag2 <- model2network("[latitude][longitude][BPB][Zest|BPB:latitude:longitude][Rent|BPB:latitude:longitude][ROI|Zest:Rent]")
dag3 <- model2network("[latlng][Type][BPB|Type][Zest|BPB:latlng:Type][Rent|BPB:latlng][ROI|Zest:Rent]")
dag4 <- model2network("[latlng][BPB][Zest|BPB:latlng][Rent|BPB:latlng][ROI|Zest:Rent]")
dag5 <- model2network("[Neigh][BPB][Zest|BPB:Neigh][Rent|BPB][ROI|Zest:Rent]")


dags[[1]] <- dag1
dags[[2]] <- dag2
dags[[3]] <- dag3
dags[[4]] <- dag4
dags[[5]] <- dag5

graphviz.plot(dag1)
graphviz.plot(dag2)
graphviz.plot(dag3)
graphviz.plot(dag4)
graphviz.plot(dag5)



```




```{r}

fit_models <- list()
for (i in 1:length(dags)) {
  fit_models[[i]] <- bn.fit(dags[[i]], df[,nodes(dags[[i]])])
}

```


```{r}
d_sep <- bnlearn:::dseparation
get_subsets <- function(model, subset_size){
    vars <- nodes(model)
    pairs <- combn(x = vars, 2, list)
    arg_sets <- list()

    for(pair in pairs){
      others <- setdiff(vars, pair)
      conditioning_sets <- unlist(lapply(0:subset_size, function(.x) combn(others, .x, list)), recursive = F)
      for(set in conditioning_sets){
        args <- list(x = pair[1], y = pair[2], z = set)
        arg_sets <- c(arg_sets, list(args))
      }
    }
      return(arg_sets)
}

dag_subsets <- list()
for (i in 1:length(dags)) {
  dag <- dags[[i]]
  dag_subsets[[i]] <- get_subsets(dag, subset_size = length(nodes(dag)) - 2)
} 


```



```{r}

get_d_sep_statments <- function (model, subsets){
  d_sep_list <- list()
  for(arg in subsets){
    if(d_sep(bn=model, x=arg$x, y=arg$y, z=arg$z)){
      args <- list(x = arg$x, y = arg$y, z = arg$z)
      d_sep_list <- c(d_sep_list, list(args))
    }
  
  }
  return(d_sep_list)
}

dag_dsep_lists <- list()
for (i in 1:length(dags)) {
  dag_dsep_lists[[i]] <- get_d_sep_statments(dags[[i]], dag_subsets[[i]])
  print(length(dag_dsep_lists[[i]]))
}

```



```{r}
get_CI_sets = function(subsets, data){
  ci_sets = list()
  for(arg in subsets){
    test_outcome <- ci.test(arg$x, arg$y, arg$z, data)
    alpha <- .05
    if(test_outcome$p.value > alpha){
      args <- list(x = arg$x, y = arg$y, z = arg$z)
      ci_sets <- c(ci_sets, list(args))
    }
  }
  return(ci_sets)
}

dag_ci_sets <- list()

for (i in 1:length(dags)) {
  dag_ci_sets[[i]] <- get_CI_sets(dag_subsets[[i]], df[,nodes(dags[[i]])])
  print(length(dag_ci_sets[[i]]))
}

```



```{r}


d_sep_list <- dag_dsep_lists[[5]]
ci_test <- dag_ci_sets[[5]]
for (c in ci_test) {
  found <- FALSE
  for(d in d_sep_list){
      if (isTRUE(all.equal(d,c))){
        found <- TRUE
      }
  }
  if (!found & length(c$z) == 0) {
    print(c)
  }
}

```



```{r}
eval_GM_and_F <- function (d_sep_list, ci_sets){
    count <- 0
    for(d in d_sep_list){
      for(c in ci_sets){

        if (isTRUE(all.equal(d,c))){
          count <- count + 1
          break
        }

      }
    }
    return(c(count/length(d_sep_list), count/length(ci_sets)))
}

gmfs <- list()

for (i in 1:length(dags)) {
  gmfs[[i]] <- eval_GM_and_F(dag_dsep_lists[[i]], dag_ci_sets[[i]])
  print(gmfs[[i]])
}

```

```{r}

fit_models[[5]]

```


